FROM node:alpine as builder
WORKDIR /src
COPY ./my-app-frontend /src
RUN npm install \
    && npm run build

FROM nginx:alpine as exe
WORKDIR /target
COPY --from=builder /src/nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /src/dist /usr/share/nginx/html
EXPOSE 80
ENTRYPOINT nginx -g "daemon off;"
