version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: dockerfile-web
    depends_on:
      - redis
      - mongodb
    networks:
      - inner
    ports:
      - "18190:8190"
    tty: true
    restart: on-failure
  frontend:
    build:
      context: .
      dockerfile: dockerfile-vue
    networks:
      - inner
    ports:
      - "3000:80"
    restart: on-failure
  redis:
    image: redis:alpine
    networks:
      - inner
    ports:
      - ":6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=""
    restart: always
    command: redis-server --appendonly yes
  mongodb:
    image: mongo:latest
    networks:
      - inner
    ports:
      - ":27017"
    volumes:
      - mongodb_data:/data/db
    restart: always
    command: mongod
networks:
  inner:
volumes:
  redis_data:
  mongodb_data: