export class Constant {
    static ACCESS_TOKEN: string = "access_token"
    static REFRESH_TOKEN: string = "refresh_token"
    static AUTHENTICATED: string = "authenticated"
    static LAST_VERIFY_CODE_SEND_TIMESTAMP = "last_verify_code_send_timestamp"
    static DRAFT_INTERVAL_CANCEL_LIST = "draft_interval_cancel_list"
    static DRAFT_ARTICLE_ID = "draft_article_id"
    static ARTICLE_TITLE = "article_title"
    static ARTICLE_CONTENT = "article_content"
    static UPDATE_ARTICLE_ID = "update_article_id"
    static ARTICLE_ID_PREFIX = "article_id_"
    static LOCAL_COORDINATE = "local_coordinate"
    static LOCAL_CITY = "local_city"
    static EDITOR_TYPE = "editor_type"
}